# Generated by Django 5.0.3 on 2024-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='category_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
