# Generated by Django 5.0.3 on 2024-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_fashionproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionproduct',
            name='url',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
